eureka:
  client:
    serviceUrl:
      defaultZone: http://119.23.22.99:8888/eureka/
server:
  port: 7777
spring:
  application:
    name: good
  profiles:
    active: prod
  ssh:
    host: 119.23.22.99
    user: root
    pwd: Leafqun@yeah.net
    port: 22
    local_port: 3307
    remote_host: localhost
    remote_port: 3306
  cache:
    ehcache:
      config: classpath:ehcache.xml
    type: ehcache
  redis:
    database: 0
    host: 119.23.22.99
    port: 6379
    password:
    timeout: 2000s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15
---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3307/score_mall?characterEncoding=UTF-8&useUnicode=true&useSSL=false